import { writeFileSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";

/**
 * HTML Formatter
 * Generates a self-contained HTML report and opens it in the browser.
 */

export function formatHTML(report) {
  const data = JSON.stringify(report, null, 2);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>git-vision Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: #0d1117;
      color: #c9d1d9;
      padding: 2rem;
      max-width: 1100px;
      margin: 0 auto;
    }
    h1 { color: #58a6ff; font-size: 1.8rem; margin-bottom: 0.3rem; }
    h2 { color: #f0f6fc; font-size: 1.2rem; margin: 2rem 0 1rem; border-bottom: 1px solid #21262d; padding-bottom: 0.5rem; }
    .subtitle { color: #8b949e; font-size: 0.9rem; margin-bottom: 2rem; }
    .score-card {
      background: #161b22;
      border: 1px solid #30363d;
      border-radius: 12px;
      padding: 1.5rem;
      text-align: center;
      margin-bottom: 2rem;
    }
    .score-big {
      font-size: 3.5rem;
      font-weight: 700;
    }
    .score-big.good { color: #3fb950; }
    .score-big.fair { color: #d29922; }
    .score-big.bad { color: #f85149; }
    .grade { font-size: 1.1rem; margin-top: 0.3rem; }
    .breakdown {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      gap: 1rem;
      margin-top: 1.5rem;
    }
    .breakdown-item {
      background: #0d1117;
      border-radius: 8px;
      padding: 1rem;
      text-align: center;
    }
    .breakdown-label { color: #8b949e; font-size: 0.8rem; text-transform: uppercase; }
    .breakdown-value { font-size: 1.5rem; font-weight: 700; margin-top: 0.3rem; }
    .bar-container {
      width: 100%;
      height: 6px;
      background: #21262d;
      border-radius: 3px;
      margin-top: 0.5rem;
      overflow: hidden;
    }
    .bar-fill {
      height: 100%;
      border-radius: 3px;
      transition: width 0.5s;
    }
    .bar-fill.good { background: #3fb950; }
    .bar-fill.fair { background: #d29922; }
    .bar-fill.bad { background: #f85149; }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 0.5rem 0;
    }
    th {
      text-align: left;
      color: #8b949e;
      font-weight: 500;
      font-size: 0.8rem;
      text-transform: uppercase;
      padding: 0.6rem 0.8rem;
      border-bottom: 1px solid #21262d;
    }
    td {
      padding: 0.6rem 0.8rem;
      border-bottom: 1px solid #161b22;
      font-size: 0.9rem;
    }
    tr:hover td { background: #161b22; }
    .risk-bar {
      display: inline-block;
      height: 12px;
      border-radius: 2px;
      vertical-align: middle;
    }
    .risk-high { background: #f85149; }
    .risk-medium { background: #d29922; }
    .risk-low { background: #3fb950; }
    .tag {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 12px;
      font-size: 0.75rem;
      font-weight: 500;
    }
    .tag-high { background: #f8514922; color: #f85149; }
    .tag-medium { background: #d2992222; color: #d29922; }
    .tag-low { background: #3fb95022; color: #3fb950; }
    .tag-cross { background: #d2992233; color: #d29922; }
    .recommendation {
      padding: 0.8rem 1rem;
      border-left: 3px solid #30363d;
      margin: 0.5rem 0;
      background: #161b22;
      border-radius: 0 6px 6px 0;
    }
    .recommendation.high { border-left-color: #f85149; }
    .recommendation.medium { border-left-color: #d29922; }
    .recommendation.low { border-left-color: #3fb950; }
    .footer { margin-top: 3rem; color: #484f58; font-size: 0.8rem; text-align: center; }
    .coupling-pair {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      padding: 0.5rem 0;
      border-bottom: 1px solid #161b22;
    }
    .coupling-arrow { color: #58a6ff; }
    .coupling-degree { font-weight: 600; }
  </style>
</head>
<body>
  <h1>git-vision</h1>
  <div class="subtitle" id="subtitle"></div>

  <div id="score-section"></div>
  <div id="hotspots-section"></div>
  <div id="bus-factor-section"></div>
  <div id="coupling-section"></div>
  <div id="code-age-section"></div>
  <div id="contributors-section"></div>
  <div id="recommendations-section"></div>

  <div class="footer">
    Generated by git-vision &middot; <a href="https://npmjs.com/package/git-vision" style="color:#58a6ff">npmjs.com/package/git-vision</a>
  </div>

  <script>
    const report = ${data};

    // Subtitle
    document.getElementById('subtitle').textContent =
      (report.repoStats?.totalCommits?.toLocaleString() || '?') + ' commits · ' +
      (report.repoStats?.totalAuthors || '?') + ' contributors · ' +
      (report.repoStats?.currentBranch || '?');

    // Health Score
    if (report.healthScore) {
      const hs = report.healthScore;
      const scoreClass = hs.overall >= 75 ? 'good' : hs.overall >= 50 ? 'fair' : 'bad';
      const breakdownHTML = Object.entries(hs.scores).map(([key, val]) => {
        const barClass = val >= 70 ? 'good' : val >= 40 ? 'fair' : 'bad';
        return '<div class="breakdown-item">' +
          '<div class="breakdown-label">' + key + '</div>' +
          '<div class="breakdown-value">' + val + '</div>' +
          '<div class="bar-container"><div class="bar-fill ' + barClass + '" style="width:' + val + '%"></div></div>' +
        '</div>';
      }).join('');

      document.getElementById('score-section').innerHTML =
        '<div class="score-card">' +
          '<div class="score-big ' + scoreClass + '">' + hs.overall + '/100</div>' +
          '<div class="grade">' + hs.grade.letter + ' — ' + hs.grade.label + '</div>' +
          '<div class="breakdown">' + breakdownHTML + '</div>' +
        '</div>';
    }

    // Hotspots
    if (report.hotspots && report.hotspots.results.length) {
      const rows = report.hotspots.results.map(r => {
        const barClass = r.normalizedScore >= 70 ? 'risk-high' : r.normalizedScore >= 30 ? 'risk-medium' : 'risk-low';
        return '<tr>' +
          '<td><span class="risk-bar ' + barClass + '" style="width:' + r.normalizedScore + 'px"></span> ' + r.normalizedScore + '</td>' +
          '<td>' + r.path + '</td>' +
          '<td>' + r.churn + '</td>' +
          '<td>' + r.loc + '</td>' +
          '<td>' + r.authors + '</td></tr>';
      }).join('');

      document.getElementById('hotspots-section').innerHTML =
        '<h2>Hotspots</h2>' +
        '<table><tr><th>Risk</th><th>File</th><th>Churn</th><th>LOC</th><th>Authors</th></tr>' +
        rows + '</table>';
    }

    // Bus Factor
    if (report.busFactor && report.busFactor.results.length) {
      const rows = report.busFactor.results.filter(r => r.isRisky).slice(0, 10).map(r => {
        const pct = r.topOwner ? Math.round(r.topOwner.percentage * 100) : 0;
        const tagClass = pct >= 90 ? 'tag-high' : pct >= 80 ? 'tag-medium' : 'tag-low';
        return '<tr>' +
          '<td>' + r.path + '</td>' +
          '<td>' + r.busFactor + '</td>' +
          '<td>' + (r.topOwner?.author || '—') + '</td>' +
          '<td><span class="tag ' + tagClass + '">' + pct + '%</span></td></tr>';
      }).join('');

      document.getElementById('bus-factor-section').innerHTML =
        '<h2>Bus Factor Risk</h2>' +
        '<table><tr><th>File</th><th>Bus Factor</th><th>Top Owner</th><th>Ownership</th></tr>' +
        rows + '</table>';
    }

    // Coupling
    if (report.coupling && report.coupling.results.length) {
      const pairs = report.coupling.results.slice(0, 10).map(c => {
        const cross = !c.sameModule ? ' <span class="tag tag-cross">CROSS-MODULE</span>' : '';
        return '<div class="coupling-pair">' +
          '<span>' + c.fileA + '</span>' +
          '<span class="coupling-arrow">&harr;</span>' +
          '<span>' + c.fileB + '</span>' +
          '<span class="coupling-degree">' + c.degreePercent + '%</span>' +
          cross + '</div>';
      }).join('');

      document.getElementById('coupling-section').innerHTML =
        '<h2>Change Coupling</h2>' + pairs;
    }

    // Code Age
    if (report.codeAge) {
      let html = '<h2>Code Age</h2>';
      const s = report.codeAge.stats;
      html += '<p style="margin:0.5rem 0;color:#8b949e">' +
        'Ancient: ' + (s.ancient||0) + ' · Stale: ' + (s.stale||0) +
        ' · Aging: ' + (s.aging||0) + ' · Active: ' + (s.active||0) +
        ' · Volatile: ' + (s.volatile||0) + '</p>';

      if (report.codeAge.volatileFiles?.length) {
        html += '<h3 style="color:#d2a8ff;margin:1rem 0 0.5rem;font-size:0.95rem">Volatile Files</h3>';
        html += report.codeAge.volatileFiles.slice(0,5).map(f =>
          '<div style="padding:0.3rem 0;border-bottom:1px solid #161b22">' +
          f.path + ' — <strong>' + f.recentCommits + ' recent</strong> (avg ' + f.avgMonthlyChurn + '/mo)</div>'
        ).join('');
      }
      document.getElementById('code-age-section').innerHTML = html;
    }

    // Contributors
    if (report.contributors && report.contributors.topContributors.length) {
      const rows = report.contributors.topContributors.slice(0, 10).map(c =>
        '<tr><td>' + c.author + '</td><td>' + c.commits + '</td><td>' + c.percentage + '%</td></tr>'
      ).join('');

      document.getElementById('contributors-section').innerHTML =
        '<h2>Contributors</h2>' +
        '<table><tr><th>Author</th><th>Commits</th><th>Share</th></tr>' +
        rows + '</table>';
    }

    // Recommendations
    if (report.healthScore?.recommendations?.length) {
      const recs = report.healthScore.recommendations.map(r =>
        '<div class="recommendation ' + r.severity + '">' + r.message + '</div>'
      ).join('');
      document.getElementById('recommendations-section').innerHTML =
        '<h2>Recommendations</h2>' + recs;
    }
  </script>
</body>
</html>`;
}

export async function writeAndOpenHTML(report) {
  const html = formatHTML(report);
  const filePath = join(tmpdir(), `git-vision-report-${Date.now()}.html`);
  writeFileSync(filePath, html, "utf-8");

  // Dynamic import for `open` package
  const { default: open } = await import("open");
  await open(filePath);

  return filePath;
}
