import chalk from "chalk";
import Table from "cli-table3";
import boxen from "boxen";

const RISK_BAR_WIDTH = 10;

/**
 * Terminal Formatter
 * Beautiful, color-coded terminal output for git-vision analysis results.
 */

export function formatTerminal(report) {
  const lines = [];

  lines.push(renderHeader(report.repoStats));
  lines.push("");

  if (report.healthScore) {
    lines.push(renderHealthScore(report.healthScore));
    lines.push("");
  }

  if (report.hotspots) {
    lines.push(renderHotspots(report.hotspots));
    lines.push("");
  }

  if (report.busFactor) {
    lines.push(renderBusFactor(report.busFactor));
    lines.push("");
  }

  if (report.coupling) {
    lines.push(renderCoupling(report.coupling));
    lines.push("");
  }

  if (report.codeAge) {
    lines.push(renderCodeAge(report.codeAge));
    lines.push("");
  }

  if (report.contributors) {
    lines.push(renderContributors(report.contributors));
    lines.push("");
  }

  if (report.healthScore && report.healthScore.recommendations.length > 0) {
    lines.push(renderRecommendations(report.healthScore.recommendations));
    lines.push("");
  }

  lines.push(chalk.dim("  Generated by git-vision • https://npmjs.com/package/git-vision"));
  lines.push("");

  return lines.join("\n");
}

function renderHeader(stats) {
  const title = chalk.bold.white("git-vision");
  const subtitle = chalk.dim("Repository Health Report");

  const info = [
    `${chalk.cyan(stats.totalCommits.toLocaleString())} commits`,
    `${chalk.cyan(stats.totalAuthors)} contributors`,
    `${chalk.dim("branch:")} ${chalk.white(stats.currentBranch)}`,
  ].join(chalk.dim(" · "));

  return boxen(`${title}  ${subtitle}\n${info}`, {
    padding: { top: 0, bottom: 0, left: 1, right: 1 },
    borderColor: "cyan",
    borderStyle: "round",
    dimBorder: false,
  });
}

function renderHealthScore(health) {
  const { overall, grade, scores } = health;

  const scoreColor =
    grade.color === "green" ? chalk.green :
    grade.color === "yellow" ? chalk.yellow : chalk.red;

  const bigScore = scoreColor.bold(`${overall}/100`);
  const gradeText = scoreColor(`${grade.letter} — ${grade.label}`);

  const breakdown = [
    `  ${scoreLabel("Hotspots")}  ${miniBar(scores.hotspots)} ${chalk.dim(scores.hotspots + "/100")}`,
    `  ${scoreLabel("Bus Factor")} ${miniBar(scores.busFactor)} ${chalk.dim(scores.busFactor + "/100")}`,
    `  ${scoreLabel("Coupling")}  ${miniBar(scores.coupling)} ${chalk.dim(scores.coupling + "/100")}`,
    `  ${scoreLabel("Code Age")}  ${miniBar(scores.codeAge)} ${chalk.dim(scores.codeAge + "/100")}`,
    `  ${scoreLabel("Team")}      ${miniBar(scores.contributors)} ${chalk.dim(scores.contributors + "/100")}`,
  ].join("\n");

  return [
    sectionTitle("HEALTH SCORE"),
    `  ${bigScore}  ${gradeText}`,
    "",
    breakdown,
  ].join("\n");
}

function renderHotspots(hotspots) {
  if (hotspots.results.length === 0) {
    return sectionTitle("HOTSPOTS") + "\n" + chalk.dim("  No hotspots detected.");
  }

  const table = new Table({
    head: ["", "File", "Churn", "LOC", "Authors"].map((h) => chalk.dim(h)),
    chars: tableChars(),
    style: { head: [], border: ["dim"] },
    colWidths: [14, 45, 8, 8, 9],
  });

  for (const r of hotspots.results) {
    table.push([
      riskBar(r.normalizedScore),
      truncatePath(r.path, 43),
      chalk.white(r.churn),
      chalk.dim(r.loc),
      chalk.dim(r.authors),
    ]);
  }

  const summary = chalk.dim(
    `  ${hotspots.stats.highRisk} high risk · ${hotspots.stats.mediumRisk} medium · ${hotspots.stats.lowRisk} low · ${hotspots.total} files analyzed`
  );

  return [sectionTitle("HOTSPOTS", "fire"), table.toString(), summary].join("\n");
}

function renderBusFactor(bf) {
  if (bf.results.length === 0) {
    return sectionTitle("BUS FACTOR") + "\n" + chalk.dim("  No bus factor risks detected.");
  }

  const riskyFiles = bf.results.filter((f) => f.isRisky);

  const table = new Table({
    head: ["File", "Bus Factor", "Top Owner", "Ownership"].map((h) => chalk.dim(h)),
    chars: tableChars(),
    style: { head: [], border: ["dim"] },
    colWidths: [40, 12, 20, 12],
  });

  for (const r of riskyFiles.slice(0, 10)) {
    const ownerPct = r.topOwner ? Math.round(r.topOwner.percentage * 100) : 0;
    const ownerColor = ownerPct >= 90 ? chalk.red : ownerPct >= 80 ? chalk.yellow : chalk.white;

    table.push([
      truncatePath(r.path, 38),
      r.busFactor === 1 ? chalk.red.bold("1") : chalk.yellow(r.busFactor),
      chalk.dim(r.topOwner ? truncate(r.topOwner.author, 18) : "—"),
      ownerColor(`${ownerPct}%`),
    ]);
  }

  const summary = chalk.dim(
    `  ${bf.stats.riskyFiles} risky files (${bf.stats.riskyPercentage}%) · avg bus factor: ${bf.stats.avgBusFactor}`
  );

  return [sectionTitle("BUS FACTOR", "warning"), table.toString(), summary].join("\n");
}

function renderCoupling(coupling) {
  if (coupling.results.length === 0) {
    return sectionTitle("CHANGE COUPLING") + "\n" + chalk.dim("  No significant coupling detected.");
  }

  const lines = [sectionTitle("CHANGE COUPLING", "link")];

  for (const c of coupling.results.slice(0, 8)) {
    const arrow = c.sameModule ? chalk.dim(" <-> ") : chalk.yellow(" <-> ");
    const degreeColor = c.degree >= 0.7 ? chalk.red : c.degree >= 0.5 ? chalk.yellow : chalk.white;
    const badge = c.sameModule ? "" : chalk.bgYellow.black(" CROSS-MODULE ");

    lines.push(
      `  ${truncatePath(c.fileA, 30)}${arrow}${truncatePath(c.fileB, 30)}  ${degreeColor(c.degreePercent + "%")}  ${badge}`
    );
  }

  lines.push("");
  lines.push(
    chalk.dim(
      `  ${coupling.stats.crossModuleCouplings} cross-module · ${coupling.stats.withinModuleCouplings} within-module · ${coupling.total} total couplings`
    )
  );

  return lines.join("\n");
}

function renderCodeAge(codeAge) {
  const lines = [sectionTitle("CODE AGE", "clock")];

  // Status distribution bar
  const total = codeAge.total || 1;
  const dist = codeAge.stats;
  lines.push(
    `  ${chalk.red("ancient:" + dist.ancient)} · ${chalk.yellow("stale:" + dist.stale)} · ${chalk.dim("aging:" + dist.aging)} · ${chalk.green("active:" + dist.active)} · ${chalk.magenta("volatile:" + dist.volatile)}`
  );
  lines.push("");

  if (codeAge.volatileFiles.length > 0) {
    lines.push(chalk.magenta.bold("  Volatile (sudden change spikes):"));
    for (const f of codeAge.volatileFiles.slice(0, 5)) {
      lines.push(
        `  ${chalk.magenta("~")} ${truncatePath(f.path, 45)}  ${chalk.white(f.recentCommits + " recent")} ${chalk.dim("(avg " + f.avgMonthlyChurn + "/mo)")}`
      );
    }
    lines.push("");
  }

  if (codeAge.staleFiles.length > 0) {
    lines.push(chalk.yellow.bold("  Stale (untouched for months):"));
    for (const f of codeAge.staleFiles.slice(0, 5)) {
      lines.push(
        `  ${chalk.yellow("○")} ${truncatePath(f.path, 45)}  ${chalk.dim(f.daysSinceLastChange + " days ago")}`
      );
    }
  }

  return lines.join("\n");
}

function renderContributors(contrib) {
  const lines = [sectionTitle("CONTRIBUTORS", "people")];

  // Top contributors
  if (contrib.topContributors.length > 0) {
    lines.push(chalk.bold("  Top Contributors:"));
    for (const c of contrib.topContributors.slice(0, 5)) {
      const bar = miniBar(c.percentage);
      lines.push(
        `  ${bar} ${chalk.white(truncate(c.author, 25))}  ${chalk.cyan(c.commits)} commits ${chalk.dim("(" + c.percentage + "%)")}`
      );
    }
    lines.push("");
  }

  // Module ownership
  if (contrib.modules.length > 0) {
    lines.push(chalk.bold("  Module Ownership:"));
    const table = new Table({
      head: ["Module", "Files", "Commits", "Authors", "Fragmentation"].map((h) => chalk.dim(h)),
      chars: tableChars(),
      style: { head: [], border: ["dim"] },
      colWidths: [25, 8, 10, 9, 16],
    });

    for (const m of contrib.modules.slice(0, 8)) {
      const fragColor =
        m.fragmentationLevel === "high" ? chalk.red :
        m.fragmentationLevel === "medium" ? chalk.yellow : chalk.green;

      table.push([
        chalk.white(truncate(m.module, 23)),
        chalk.dim(m.files),
        chalk.dim(m.totalCommits),
        chalk.dim(m.uniqueAuthors),
        fragColor(m.fragmentationLevel + " (" + m.fragmentation + ")"),
      ]);
    }

    lines.push(table.toString());
  }

  return lines.join("\n");
}

function renderRecommendations(recommendations) {
  const lines = [sectionTitle("RECOMMENDATIONS", "bulb")];

  for (const r of recommendations) {
    const icon =
      r.severity === "high" ? chalk.red("!!") :
      r.severity === "medium" ? chalk.yellow(" !") :
      chalk.dim(" i");
    const color =
      r.severity === "high" ? chalk.white :
      r.severity === "medium" ? chalk.white :
      chalk.dim;

    lines.push(`  ${icon} ${color(r.message)}`);
  }

  return lines.join("\n");
}

// ─── Helpers ────────────────────────────────────────────────

const ICONS = {
  fire: chalk.red("*"),
  warning: chalk.yellow("!"),
  link: chalk.cyan("~"),
  clock: chalk.blue("@"),
  people: chalk.green("#"),
  bulb: chalk.yellow(">"),
};

function sectionTitle(title, icon) {
  const prefix = icon ? ICONS[icon] + " " : "";
  return chalk.bold.white(`  ${prefix}${title}`);
}

function riskBar(score) {
  const filled = Math.round((score / 100) * RISK_BAR_WIDTH);
  const empty = RISK_BAR_WIDTH - filled;

  const color =
    score >= 70 ? chalk.red :
    score >= 30 ? chalk.yellow :
    chalk.green;

  return color("\u2588".repeat(filled)) + chalk.dim("\u2591".repeat(empty));
}

function miniBar(percentage) {
  const width = 8;
  const filled = Math.round((percentage / 100) * width);
  const empty = width - filled;

  const color =
    percentage >= 70 ? chalk.green :
    percentage >= 40 ? chalk.yellow :
    chalk.red;

  return color("\u2588".repeat(filled)) + chalk.dim("\u2591".repeat(empty));
}

function scoreLabel(label) {
  return chalk.dim(label.padEnd(12));
}

function truncatePath(path, maxLen) {
  if (path.length <= maxLen) return chalk.white(path);
  const start = path.slice(0, 10);
  const end = path.slice(-(maxLen - 13));
  return chalk.white(start + chalk.dim("...") + end);
}

function truncate(str, maxLen) {
  if (str.length <= maxLen) return str;
  return str.slice(0, maxLen - 1) + "\u2026";
}

function tableChars() {
  return {
    top: "\u2500", "top-mid": "\u252C", "top-left": "\u250C", "top-right": "\u2510",
    bottom: "\u2500", "bottom-mid": "\u2534", "bottom-left": "\u2514", "bottom-right": "\u2518",
    left: "\u2502", "left-mid": "\u251C", mid: "\u2500", "mid-mid": "\u253C",
    right: "\u2502", "right-mid": "\u2524", middle: "\u2502",
  };
}
